---

- name: "Copy artifact from local and unarchive to remote host"
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: Install dependencies
  npm:
    path: ~/

- name: Run build
  command: npm run build
  args:
    chdir: ~/

- name: "Stop previous pm2"
  command: pm2 stop default
  ignore_errors: true
  args:
    chdir: ~/

- name: "Start process again"
  command: pm2 start npm -- start
  args:
    chdir: ~/