---

- name: "Copy artifact from local and unarchive to remote host"
  unarchive:
    src: ./artifact.tar.gz
    dest: ~/artifact

- name: Install dependencies
  npm:
    path: ~/artifact

- name: "Stop previous pm2"
  command: pm2 stop default
  args:
    chdir: artifact/

- name: "Start process again"
  command: pm2 start npm -- start
  args:
    chdir: artifact/